### ISSUE TITLE
Upgrade to .NET Core 3 

### ISSUE THREAD

**Issue by genuinefafa** [johnph/simple-transaction#3]
What about upgrading to latest .NET Core release?

I'm trying to start a new project, found this, and began to smile since is so well documented and feels so right. 🥇

**Comment by johnph** [comment]
I'm writing Part 2 of Simple Transaction with few more microservices added to the list to demonstrate Event Sourcing and CQRS pattern. I'll release the next version of it in .Net Core 3. coming soon...

I'm glad you liked it and thank you for the comments. :)
